export const capabilities = [
  "bernini-r-edit",
  "bernini-r-ref-edit",
  "bg-remove",
  "blender-headless",
  "brand_kit_create",
  "cad-render",
  "cad-step",
  "cad-validate",
  "chatterbox-tts",
  "context_kit_create",
  "cosmos-3-image",
  "create_cad_model",
  "export_stl",
  "ffmpeg-audio-mix",
  "ffmpeg-burn-subtitles",
  "ffmpeg-colorgrade",
  "ffmpeg-concat",
  "ffmpeg-export",
  "ffmpeg-grid",
  "ffmpeg-loop",
  "ffmpeg-mux",
  "ffmpeg-overlay",
  "flux-3-draft-enhance",
  "flux-3-draft-extend",
  "flux-3-draft-i2v",
  "flux-3-draft-t2v",
  "flux-3-extend",
  "flux-3-i2v",
  "flux-3-keyframes",
  "flux-3-t2v",
  "flux-dev",
  "flux-erase",
  "format-convert",
  "gemini-text",
  "gemini-tts",
  "gpt-image",
  "gpt-image-edit",
  "grok-imagine-video",
  "grok-imagine-video-ref2v",
  "grok-imagine-video-t2v",
  "heygen-filler-removal",
  "hyperframes-caption",
  "hyperframes-lower-third",
  "hyperframes-render",
  "ideogram-v4",
  "inworld-tts",
  "kling-o3-i2v",
  "kling-o3-ref2v",
  "kling-v3-turbo-i2v",
  "kling-v3-turbo-pro-t2v",
  "kling-v3-turbo-t2v",
  "kontext-edit",
  "krea-2-large",
  "krea-2-lora",
  "krea-2-lora-training",
  "krea-2-os",
  "lipsync",
  "logo_capture",
  "ltx-i2v",
  "ltx-q-i2v",
  "ltx-q-ref2v",
  "ltx-q-t2v",
  "mai-image-2.5",
  "marlin-video",
  "minimax-h3-i2v",
  "minimax-h3-ref2v",
  "minimax-h3-t2v",
  "music",
  "nano-banana",
  "nemotron-asr",
  "pixelcut-product-photo",
  "pixverse-i2v",
  "pixverse-t2v",
  "pixverse-transition",
  "place_subject",
  "qwen-image-3-edit",
  "qwen-image-3-t2i",
  "recraft-v4",
  "refine_cad_model",
  "sam3",
  "seed-audio",
  "seedance-i2v",
  "seedance-mini-i2v",
  "seedance-mini-t2v",
  "seedream-5-lite",
  "sensenova-u1-infographic",
  "sonilo-t2m",
  "stock-footage-fetch",
  "sync-lipsync-v3",
  "talking-head",
  "transcribe",
  "tripo-i3d",
  "veed-lipsync-v2",
  "veo-transition",
  "void-inpaint",
  "whisper-word",
  "wizper",
  "yolo-segment",
] as const;

export const featuredMedia = {
  studio: {
    id: "studio-crab",
    kind: "video" as const,
    src: "/media-2026-08-08-141651/crab.mp4",
    alt: "Crab production video",
  },
  routing: {
    id: "routing-capabilities",
    kind: "video" as const,
    src: "/media-2026-08-08-141651/capabilities.mp4",
    alt: "Livepeer Agent capabilities video",
  },
  pricing: {
    id: "pricing-usage",
    kind: "image" as const,
    src: "/media-2026-08-08-145138/usage.png",
    alt: "Livepeer Agent usage and balance screen",
    fit: "portrait" as const,
    accentFrame: true,
  },
  workflow: {
    id: "workflow-demo",
    kind: "image" as const,
    src: "/media-2026-08-08-174438/demosc.png",
    alt: "Livepeer Agent workflow demo with three production images and reusable prompts",
    fit: "portrait" as const,
    accentFrame: true,
  },
  compatible: {
    id: "compatible-claude-code",
    kind: "video" as const,
    src: "/media-2026-08-08-145310/claudecode.mp4",
    alt: "Livepeer Agent running with Claude Code",
    coverBottomEdge: true,
  },
} as const;

export const authModalMedia = {
  src: "/media-2026-08-08-150247/crab-beach.mp4",
  alt: "Crab walking along the beach",
} as const;

export const networkImages = Array.from({ length: 13 }, (_, index) => ({
  id: `network-${index + 1}`,
  kind: "image" as const,
  src: `/livepeer-ui-2026-08-08/network/network-${index + 1}.webp`,
  alt: `Livepeer production still ${index + 1}`,
}));

export const compatibilityMarks = [
  {
    name: "Claude",
    src: "/model-family-logos-2026-08-08-182324/claude.svg",
  },
  {
    name: "Claude Code",
    src: "/model-family-logos-2026-08-08-182324/claude-code.svg",
  },
  {
    name: "OpenAI",
    src: "/model-family-logos-2026-08-08-182324/openai.svg",
  },
  {
    name: "Nous",
    src: "/model-family-logos-2026-08-08-182324/nous-research.svg",
  },
] as const;
